### ISSUE TITLE
Support Spark 3.2.2+

### ISSUE THREAD

**Issue by megri** [vincenzobaz/spark-scala3#20]
The field `isDeterministic: Boolean = true` was added to the [case class Invoke](https://github.com/apache/spark/blob/78a5825fe266c0884d2dd18cbca9625fa258d7f7/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/objects/objects.scala#L350-L358) somewhere between version 3.2.0 -> 3.2.2 (commit where this happened: https://github.com/apache/spark/commit/3860ac5d2313d438c25e5c46ed4e2b8b2b5227e3)

This causes the derivation to fail during compile time.

It's probably not very nice to support this across several versions of spark 🤔

**Comment by vincenzobaz** [comment]
Thank you for reporting this @megri 
This is a development and experimentation library, so it makes sense to support the latest Spark version only.
It would amazing if you could open a PR which upgrades the Spark version and supports the new field!

In the meantime you could also have a look at [Iskra](https://github.com/VirtusLab/iskra) where the derivation of encoders is done in a completely different way.
Unfortunately nowadays I do not have a lot of time to maintain this library, but let me know if you cannot open the PR and I will see if I can spare some time for it.

**Comment by megri** [comment]
Seems like all that was needed was to recompile the project with the newer dependency. 😄
