### ISSUE TITLE
Could this library support udfs? 

### ISSUE THREAD

**Issue by jtnystrom** [vincenzobaz/spark-scala3#24]
Hello, thanks for your work on this library! I'm trying to port a large-ish Spark project to Scala 3, mostly out of curiosity at this point.
This library solved a lot of my compile errors.
My next main source of problems is UDFs, which I define using spark.sql.functions.udf, e.g. 

```scala
val ts = udf((xs: Array[ZeroNTBitArray]) => xs.map(_.toString))
```

Where ZeroNTBitArray is a case class. I get a lot of compiler errors like No TypeTag available for String, no TypeTag available for Array[String], etc. Obviously the definition of udfs seems to depend on the TypeTag system, which is gone in Scala 3.
However, there also seems to be another way of registering UDFs, using the Java API for this purpose, e.g. UDF1, UDF2, UDF3 etc, which doesn't need TypeTags (instead just needs to provide a DataType for the return type).

This is all thinking out loud, but I wonder if there would be scope for this library to support some kind of simple udf registration? I haven't thought too deeply about the issue at all, so feel free to disregard this if it's out of scope.

Thanks again.

**Comment by vincenzobaz** [comment]
Hello @jtnystrom, it is nice to meet a fellow Scala3-Spark adventurer. 
I confess I did not try the lib with UDFs. However, given your example, I wonder if the issue does not depend from incomplete support of collections (#15) rather than a udf issue.
Have you experimented with simpler udfs that have for arguments case classes or integers?

**Comment by jtnystrom** [comment]
Hi @vincenzobaz, thanks for your reply. Yes, I get the same issue even for primitive types, e.g.

```scala
val simple = udf((x: Long) => x + 1)
segments.select(simple($"hash"))
```

leads to the error "No TypeTag available for Long", on the line where `simple` is defined.

**Comment by vincenzobaz** [comment]
Thank you for checking and the minimized examples!

**Comment by jtnystrom** [comment]
Thanks @michael72 and @vincenzobaz for looking into this issue!

Just to let you know, the jar of version 0.2.0 of spark-scala3 on maven central now seems to contain only the scala3udf package. The scala3encoders package is gone. Was that a mistake, or should scala3encoders no longer be used? :-)

**Comment by vincenzobaz** [comment]
Hello @jtnystrom, I'll look into it, definitely a mistake if scala3encoders is not there anymore :cry: 
Publishing is always tricky

**Comment by jtnystrom** [comment]
No rush, since I grabbed the latest code from this repo manually. Thanks again for your work.

**Comment by jtnystrom** [comment]
Thanks again @michael72 and @vincenzobaz, I was finally able to run my application with Scala 3 for the first time using this new udf derivation.
