### ISSUE TITLE
Is it possible to support Option[T]?

### ISSUE THREAD

**Issue by caioquirino** [vincenzobaz/spark-scala3#27]
Hello, good afternoon!
I haven't looked a lot into this code, just started using it today and it looks very promising! Nice job so far! :)
I would like to know if you can imagine a possible way to support Option[T], so I can try to implement it.
I just want to not focus in this in case you know that it's absolutely impossible to make it work, but if you believe it's possible, I am happy to invest some time in making it work :)

Thanks!

**Comment by michael72** [comment]
Hey - 

um - I think I already did that
If you have a look at the tests [here](https://github.com/vincenzobaz/spark-scala3/blob/main/encoders/src/test/scala/sql/EncoderDerivationSpec.scala)
we already use Option[...]

However there is no release done yet with that support.

@vincenzobaz could you draft a release?

Cheers!

**Comment by vincenzobaz** [comment]
I cut the release for v0.1.6

**Comment by vincenzobaz** [comment]
@caioquirino you should thank @michael72 , I just pushed a tag 😆
