### ISSUE TITLE
 scala3encoders.given missing from 0.2.0 jar

### ISSUE THREAD

**Issue by benwbooth** [vincenzobaz/spark-scala3#29]
```cat sparktest.sc```

```
#!/usr/bin/env -S scala-cli shebang

//> using lib "io.github.vincenzobaz::spark-scala3:0.2.0"
//> using lib "org.apache.spark:spark-core_2.13:3.4.1"
//> using lib "org.apache.spark:spark-sql_2.13:3.4.1"
//> using objectWrapper

import scala3encoders.given
import scala3udf.{Udf => udf}
import org.apache.spark.sql.SparkSession

val spark = SparkSession.builder
  .appName("spark")
  .master(sys.env.getOrElse("SPARK_MASTER_URL", "local[*]"))
  .getOrCreate()
```

`./sparktest.sc`

```
Compiling project (Scala 3.3.0, JVM)
[error] ./sparktest.sc:8:8
[error] Not found: scala3encoders
[error] import scala3encoders.given
[error]        ^^^^^^^^^^^^^^
Error compiling project (Scala 3.3.0, JVM)
Compilation failed
```

```jar tf ~/.cache/coursier/v1/https/repo1.maven.org/maven2/io/github/vincenzobaz/spark-scala3_3/0.2.0/spark-scala3_3-0.2.0.jar```

```
META-INF/MANIFEST.MF
org/
org/apache/
org/apache/spark/
org/apache/spark/sql/
org/apache/spark/sql/expressions/
scala3udf/
Gen.scala
org/apache/spark/sql/expressions/Exporter$.class
org/apache/spark/sql/expressions/Exporter.class
org/apache/spark/sql/expressions/Exporter.tasty
scala3udf/Udf$.class
scala3udf/Udf.class
scala3udf/Udf.tasty

```

**Comment by vincenzobaz** [comment]
Hello @benwbooth, thank you for reporting this.
This issue was reported as a consequence of the new module for udfs being introduced.
I am not very familiar with artifact publishing but you have any suggestion I'd be happy to take a look

**Comment by adpi2** [comment]
The problem is that all sbt projects have the same artifact name and thus only one artifact was released:
https://github.com/vincenzobaz/spark-scala3/blob/b40510c201fffffe8135d34712c35fa2d78f1e49/build.sbt#L78

Each project should have a different name:
```scala
val encoders = project.in(file("encoders"))
  .settings(
     ...
    name := "spark-scala3-encoders"
  )

val udfs = project.in(file("udf"))
  .settings(
    ...
    name := "spark-scala3-udf" 
  )

**Comment by Anghammar** [comment]
I still don't get scala3encoders when adding this dependancy with `libraryDependencies += "io.github.vincenzobaz" %% "spark-scala3" % "0.2.0"` in my `build.sbt`. Is there perhaps something cached on my system? Does this work for anyone else?

**Comment by vincenzobaz** [comment]
hey @Anghammar , I am having [some problems publishing](https://github.com/vincenzobaz/spark-scala3/actions/runs/5519551859/jobs/10064955726)

**Comment by vincenzobaz** [comment]
in the meantime the snapshot version `0.2.0+2-496f87b9-SNAPSHOT` should be available

**Comment by benwbooth** [comment]
@vincenzobaz I don't see the snapshot version [here](https://central.sonatype.com/artifact/io.github.vincenzobaz/spark-scala3_3/0.2.0/versions). Can you please show where to find the snapshot version? Or alternatively, try to publish a new release? Thanks!

**Comment by Anghammar** [comment]
> @vincenzobaz I don't see the snapshot version [here](https://central.sonatype.com/artifact/io.github.vincenzobaz/spark-scala3_3/0.2.0/versions). Can you please show where to find the snapshot version? Or alternatively, try to publish a new release? Thanks!

Yeah I did not find the snapshot version either so I ended up just building the lib locally as a temporary fix.

**Comment by vincenzobaz** [comment]
You might have to enable the snapshot resolver: `https://s01.oss.sonatype.org/content/repositories/snapshots/`

**Comment by vincenzobaz** [comment]
@adpi2 would you have an idea of what is broken with our publishing?

**Comment by adpi2** [comment]
It seems something is wrong with your PGP keys. Are they expired?

**Comment by vincenzobaz** [comment]
I can publish to snapshot but not the main repo. It could be PGP keys...

**Comment by benwbooth** [comment]
@vincenzobaz I still don't see the encoders in the latest jar from the snapshot directory:

```
wget https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/vincenzobaz/spark-scala3_3/0.2.0+2-f6cbecad-SNAPSHOT/spark-scala3_3-0.2.0+2-f6cbecad-SNAPSHOT.jar
```

```
jar tf spark-scala3_3-0.2.0+2-f6cbecad-SNAPSHOT.jar
```

```
META-INF/MANIFEST.MF
org/
org/apache/
org/apache/spark/
org/apache/spark/sql/
org/apache/spark/sql/expressions/
scala3udf/
Gen.scala
org/apache/spark/sql/expressions/Exporter$.class
org/apache/spark/sql/expressions/Exporter.class
org/apache/spark/sql/expressions/Exporter.tasty
scala3udf/Udf$.class
scala3udf/Udf.class
scala3udf/Udf.tasty
```

**Comment by vincenzobaz** [comment]
@adpi2 I created new keys and it seems to be working. Great intuition!
@benwbooth could you try version 0.2.1?
