### ISSUE TITLE
Publish is broken

### ISSUE THREAD

**Issue by joan38** [vincenzobaz/spark-scala3#34]
Sounds like the published package does not contain the encoder. I believe this is because we are trying to publish udf and encoder under the same artifact [here](https://github.com/vincenzobaz/spark-scala3/blob/main/build.sbt#L80)

See content of the jar:
```
% tar tf spark-scala3_3-0.2.1.jar 
META-INF/MANIFEST.MF
org/
org/apache/
org/apache/spark/
org/apache/spark/sql/
org/apache/spark/sql/expressions/
scala3udf/
Gen.scala
org/apache/spark/sql/expressions/Exporter$.class
org/apache/spark/sql/expressions/Exporter.class
org/apache/spark/sql/expressions/Exporter.tasty
scala3udf/Udf$.class
scala3udf/Udf.class
scala3udf/Udf.tasty
```

**Comment by vincenzobaz** [comment]
Thank you for opening this issue.
We were discussing broken publish in another PR.

I do not have a lot of experience with publishing so I am having a hard with this.
I am trying to merge the two projects to simplify but testing is still red.

**Comment by vincenzobaz** [comment]
Let me know if it works :) I published the two artifacts
