### ISSUE TITLE
Spark needs to be provided

### ISSUE THREAD

**Issue by joan38** [vincenzobaz/spark-scala3#38]
The [Spark dep](https://github.com/vincenzobaz/spark-scala3/blob/main/build.sbt#L8) needs to be `provided` for the following reasons:
* We should use the version we want downstream. Some of us even have modified versions of Spark.
* Spark is included in the cluster so we don't even have it in the jar

I can do the PR if you agree. Let me know.

Thanks

**Comment by vincenzobaz** [comment]
You are right! Thank you for the suggestion
