### ISSUE TITLE
Latest Version `2.5` not available on Maven, it seems as if the publishing to Sonatype failed

### ISSUE THREAD

**Issue by ASRagab** [vincenzobaz/spark-scala3#53]
https://github.com/vincenzobaz/spark-scala3/actions/runs/6722526367/job/18271028393

Looks as if it failed to publish (for which you have my deepest sympathies).

**Comment by vincenzobaz** [comment]
thank you for signaling this (and for the sympathies 😂, I will need them).
I'll try to debug this as soon as I have time. In the meantime you can use 2.4

**Comment by vincenzobaz** [comment]
Seems to be solved [pom](https://s01.oss.sonatype.org/service/local/repositories/releases/content/io/github/vincenzobaz/spark-scala3-encoders_3/0.2.5/spark-scala3-encoders_3-0.2.5.pom)
